title: Codezilla
email: shir.mati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Sharing my daily Learnings, Tutorials and just some Thoughs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

repository: shirmati/shirmati.github.io
